global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'koa_backend'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['koa-backend:8080']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']